name: Compile PDFs

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "1 1 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: josemiguel443
        path: josemiguel443/*.pdf
